name: 'Neo4j-GenAI PR E2E Tests'

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    strategy:
      matrix:
        python-version: ['3.8', '3.12']
        neo4j-version:
          - 5
        neo4j-edition:
          - enterprise
    with:
      target: ${{ matrix.python-version }}
      python-version:  ${{ matrix.neo4j-edition }}
    services:
      t2v-transformers:
        image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2-onnx
        env:
          ENABLE_CUDA: '0'
      weaviate:
        image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
        env:
          TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
          AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
          DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
          ENABLE_MODULES: 'text2vec-transformers'
          CLUSTER_HOSTNAME: 'node1'
        ports:
          - 8080:8080
          - 50051:50051
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}-${{ matrix.neo4j-edition }}
        env:
          NEO4J_AUTH: neo4j/password
          NEO4J_ACCEPT_LICENSE_AGREEMENT: 'eval'
          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
